# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xs50MoJ4-MSkW1Dv-3D947qCh1mZDAXE
"""

import streamlit as st
import pickle

with open("models/model.pkl", "rb") as model_file:
    model = pickle.load(model_file)
with open("models/tfidf.pkl", "rb") as vectorizer_file:
    tfidf = pickle.load(vectorizer_file)

st.title("📰 Fake News Classifier")
st.subheader("Enter a news article and find out if it's real or fake.")


user_input = st.text_area("✏️ Enter news content here:")

if st.button("🔍 Predict"):
    if user_input.strip() != "":

        transformed_input = tfidf.transform([user_input])
        prediction = model.predict(transformed_input)


        if prediction[0] == 1:
            st.success("✅ The news is Real.")
        else:
            st.error("❌ The news is Fake.")
    else:
        st.warning("Please enter some news content.")